#raspimouse_on_gazebo:           #Name of the node robotNamespace
# Publisher
joint_state_controller:
  type:                        "joint_state_controller/JointStateController"
  publish_rate:                10

mobile_base_controller:        #Name of controller
  type        :                "diff_drive_controller/DiffDriveController"

  left_wheel  :                'left_wheel_joint'
  right_wheel :                'right_wheel_joint'
  publish_rate: 10               # default: 50
  pose_covariance_diagonal :   [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal:   [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation :           0.085
  wheel_radius :               0.024

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  #cmd_vel_timeout:            0.25

  # Base frame_id
  base_frame_id: base_footprint #default: base_link
  enable_odom_tf:              true

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
# /gazebo_ros_control:
#   pid_gains:
#     left_wheel_joint:
#       p:                     100.0
#       i:                     1.0
#       d:                     0.1
#     right_wheel_joint:
#       p:                     100.0
#       i:                     1.0
#       d:                     0.1
